#!/usr/bin/env bash
set -eu
set -o pipefail

max_parallel_tasks=10

git submodule init

git submodule | awk '{ print $2 }' \
  | xargs -I{} -P$max_parallel_tasks sh -c \
  "echo 'Cloning {}'
  if ! git submodule update --quiet --depth 1 '{}'
  then
    echo 'falling back to deep clone for {}'
    if ! git submodule update --quiet '{}'
    then echo '** FAILED ** {}'
    fi
  fi"
