#!/usr/bin/env sh
set -eu

max_parallel_tasks=10
ignore_file='ignore_modules.txt'
test -f $ignore_file || touch $ignore_file

#prevents git from waiting for password input on invalid/removed git URLs
export GIT_ASKPASS=/bin/echo

git submodule | awk '{ print $2 }' | grep --invert-match --fixed-strings --file=$ignore_file \
  | xargs -I'{}' -P$max_parallel_tasks sh check.sh {}
