#!/usr/bin/env bash
set -eu
set -o pipefail

max_parallel_tasks=10

git submodule | awk '{ print $2 }' \
  | xargs -I{} -P$max_parallel_tasks sh -c \
  "echo 'Checking {}'
  if cd '{}'
    then if [ -f .git ] #might be empty dir instead of proper submodule
      then git fetch --quiet && git reset --quiet --hard origin/HEAD \
        || echo ' ** Failed ** {}'
    fi
  fi"
