#!/usr/bin/env bash
set -eu
set -o pipefail

max_parallel_tasks=10

git submodule | awk '{ print $2 }' \
  | xargs -I{} --max-procs=$max_parallel_tasks bash -c \
  "echo 'Checking' {} \
  && cd {} && git fetch --quiet \
  && git reset --quiet --hard origin/HEAD \
  || echo '** FAILED **' {}"
